import Head from "next/head";
import styles from "../styles/Home.module.css";
import { GraphQLClient, gql } from "graphql-request";
import { useEffect, useState } from "react";
import BlogPost from "../components/BlogCard";
const graphcms = new GraphQLClient(
  "https://api-eu-west-2.hygraph.com/v2/cl9kbzpde310d01t9go1tdb92/master"
);

const QUERY = gql`
  query {
    posts {
      id
      title
      datePublished
      slug
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      coverPhoto {
        url
      }
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({ posts }) {
  return (
    <>
      <div className={styles.shadow}>Tell me the title!</div>

      <div className={styles.container}>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          {posts.map((post) => (
            <BlogPost
              title={post.title}
              author={post.author}
              coverPhoto={post.coverPhoto}
              key={post.id}
              datePublished={post.datePublished}
              slug={post.slug}
            />
          ))}
        </main>
      </div>
    </>
  );
}
